[package]
name = "sp"
version = "0.1.0"
authors = ["Igor <ivkovityigor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
open = "1.4.0"
yansi = "0.5.0"
pickledb = "0.4.1"
serde = "1.0.112"
